/**
 * Generates Boughtique's editorial plates.
 *
 * These are ABSTRACT, ORIGINAL artworks generated by us and served from our own
 * domain. They are decorative only and must never be presented as a photograph
 * of a purchasable product. When licensed product imagery arrives through
 * retailer/affiliate feeds it replaces these.
 *
 *   node scripts/generate-art.mjs
 */

import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'assets/img');

const W = 800;
const H = 1000;

/** Restrained neutral pairs: ground, form, hairline. */
const PALETTES = [
  { bg: '#ECE7DE', fg: '#D8D1C4', line: '#C3BAA9' },
  { bg: '#E6E3DD', fg: '#CFCABF', line: '#B7B0A3' },
  { bg: '#F0ECE6', fg: '#DCD4C8', line: '#C6BCAC' },
  { bg: '#E3E1DC', fg: '#C9C6BE', line: '#AFABA1' },
  { bg: '#EDE8E1', fg: '#D3CBBD', line: '#BBB1A0' },
  { bg: '#E8E4DA', fg: '#CEC6B6', line: '#B4AA98' },
  { bg: '#F1EDE7', fg: '#D9D2C6', line: '#C0B7A7' },
  { bg: '#E5E0D6', fg: '#CBC3B2', line: '#B1A694' },
];

/** Eight compositions. Deliberately geometric, no gradients, no illustration. */
const FORMS = [
  (p) => `<circle cx="400" cy="470" r="250" fill="${p.fg}"/>
    <path d="M150 760h500" stroke="${p.line}" stroke-width="1.5"/>`,
  (p) => `<rect x="150" y="160" width="500" height="560" fill="${p.fg}"/>
    <circle cx="400" cy="440" r="130" fill="${p.bg}"/>`,
  (p) => `<path d="M400 180a260 260 0 0 1 0 520z" fill="${p.fg}"/>
    <path d="M400 180a260 260 0 0 0 0 520" fill="none" stroke="${p.line}" stroke-width="1.5"/>`,
  (p) => `<rect x="110" y="300" width="580" height="300" fill="${p.fg}"/>
    <path d="M110 300v400M690 300v400" stroke="${p.line}" stroke-width="1.5"/>`,
  (p) => `<circle cx="300" cy="420" r="190" fill="${p.fg}"/>
    <circle cx="500" cy="580" r="190" fill="none" stroke="${p.line}" stroke-width="1.5"/>`,
  (p) => `<path d="M160 740L400 220l240 520z" fill="${p.fg}"/>
    <path d="M160 740h480" stroke="${p.line}" stroke-width="1.5"/>`,
  (p) => `<rect x="200" y="200" width="400" height="400" rx="200" fill="${p.fg}"/>
    <rect x="200" y="640" width="400" height="120" fill="none" stroke="${p.line}" stroke-width="1.5"/>`,
  (p) => `<path d="M140 620q260-420 520 0z" fill="${p.fg}"/>
    <path d="M140 620h520" stroke="${p.line}" stroke-width="1.5"/>`,
];

const hairlines = (p) =>
  Array.from({ length: 5 }, (_, i) => `<path d="M0 ${860 + i * 22}h${W}" stroke="${p.line}" stroke-opacity=".35" stroke-width="1"/>`).join('');

function plate(i) {
  const p = PALETTES[i % PALETTES.length];
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="presentation">
<rect width="${W}" height="${H}" fill="${p.bg}"/>
${FORMS[i % FORMS.length](p)}
${hairlines(p)}
</svg>`;
}

export function ogSvg() {
  const p = PALETTES[2];
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630">
<rect width="1200" height="630" fill="#faf9f7"/>
<rect x="760" width="440" height="630" fill="${p.bg}"/>
<circle cx="980" cy="315" r="190" fill="${p.fg}"/>
<path d="M80 470h600" stroke="#cec8bd" stroke-width="1.5"/>
<text x="80" y="300" font-family="Helvetica Neue, Helvetica, Arial, sans-serif" font-size="68" font-weight="600" letter-spacing="16" fill="#14130f">BOUGHTIQUE</text>
<text x="80" y="360" font-family="Helvetica Neue, Helvetica, Arial, sans-serif" font-size="24" letter-spacing="6" fill="#6e6962">FASHION DEALS DISCOVERY</text>
<text x="80" y="530" font-family="Georgia, Times New Roman, serif" font-size="40" fill="#3b3833">Fashion worth buying.</text>
</svg>`;
}

export function faviconSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
<rect width="64" height="64" rx="8" fill="#14130f"/>
<text x="32" y="44" text-anchor="middle" font-family="Helvetica Neue, Helvetica, Arial, sans-serif" font-size="38" font-weight="600" fill="#faf9f7">B</text>
</svg>`;
}

/**
 * Writes all artwork into a target directory tree. Called by the build so the
 * generated SVGs never need to live in version control.
 *
 * @param {string} dir site root to write into (e.g. dist/)
 */
export async function writeArt(dir) {
  const img = path.join(dir, 'assets/img');
  await mkdir(img, { recursive: true });
  await Promise.all([
    ...PALETTES.map((_, i) => writeFile(path.join(img, `plate-${i + 1}.svg`), plate(i))),
    writeFile(path.join(img, 'og.svg'), ogSvg()),
    writeFile(path.join(dir, 'favicon.svg'), faviconSvg()),
  ]);
  return PALETTES.length;
}

export const PLATES = PALETTES.length;

if (import.meta.url === `file://${process.argv[1]}`) {
  await writeArt(ROOT);
  console.log(`Wrote ${PALETTES.length} plates + og.svg + favicon.svg`);
}
