import { html } from './lib/html.mjs';

export const CONTACT_EMAIL = 'hello@boughtique.com';

export const pages = [
  {
    path: '/about/',
    eyebrow: 'About',
    title: 'About Boughtique',
    metaTitle: 'About Boughtique — Fashion Deals Discovery',
    metaDescription:
      'Boughtique is an independent fashion discovery engine built in Europe. We find what is worth buying and send you to the retailer.',
    lede: 'Bought + boutique. A discovery engine for fashion worth buying.',
    content: html`
      <p>
        Online fashion has a volume problem, not a taste problem. Several hundred thousand products
        are listed across European retail at any moment, most of them indistinguishable, many of
        them nominally reduced from a price nobody ever paid. Finding the genuinely good ones is
        slow, and the tools that claim to help are usually just advertising.
      </p>
      <p>
        Boughtique is being built to solve that with software. The end state is an engine that
        ingests retailer product feeds continuously, normalises them into one catalogue, works out
        what is actually a good buy, and surfaces it. No editors, no daily picks, no sponsored
        placement dressed up as curation.
      </p>

      <h2>What Boughtique is today</h2>
      <p>
        This is the first public version. It maps the European retailers and category routes that
        are genuinely worth starting from, makes them searchable and filterable, and links straight
        through to the retailer. The curation layer is deliberately thin and honest about itself:
        the catalogue you see is a seeded set of discovery routes, not a live product index.
      </p>
      <p>
        What it is not: a shop, a dropshipper, a reseller, or a blog. Boughtique never takes a
        payment, never holds stock and never stands between you and the retailer.
      </p>

      <h2>What we refuse to do</h2>
      <ul>
        <li>Publish a price, discount or stock figure we have not verified.</li>
        <li>Invent urgency, countdowns, scarcity or "deal scores" with nothing behind them.</li>
        <li>Fabricate reviews, testimonials, user counts or traffic figures.</li>
        <li>Describe a retailer as a partner when no relationship exists.</li>
        <li>Present illustrative artwork as a photograph of a product you can buy.</li>
      </ul>
      <p>
        The artwork across this site is abstract and generated by us. It sets a tone; it never
        depicts a specific garment. When authorised product imagery arrives via retailer feeds, it
        will replace it.
      </p>

      <h2>Independence</h2>
      <p>
        Boughtique currently earns nothing. There are no affiliate links, no commissions and no paid
        placements on this site today. If that changes, it will be disclosed plainly on the
        <a href="/affiliate-disclosure/">affiliate disclosure</a> page before it goes live, and
        commercial relationships will never determine ranking.
      </p>
      <p>Questions: <a href="/contact/">get in touch</a>.</p>
    `,
  },

  {
    path: '/how-it-works/',
    eyebrow: 'How it works',
    title: 'How Boughtique works',
    metaTitle: 'How Boughtique works — Fashion Deals Discovery',
    metaDescription:
      'How Boughtique discovers fashion: retailer mapping today, automated product ingestion, deal scoring and ranking next.',
    lede: 'Discovery, routing and — soon — automated ranking.',
    content: html`
      <h2>Today</h2>
      <ol>
        <li>
          <strong>We map retailers.</strong> Boughtique tracks European storefronts and the specific
          category and sale sections within them that are worth entering from.
        </li>
        <li>
          <strong>You search and filter.</strong> Search runs in your browser over the catalogue.
          Filters only ever expose facets the data can genuinely answer.
        </li>
        <li>
          <strong>You save what you like.</strong> Saved discoveries live in your browser's local
          storage. No account, nothing sent to a server.
        </li>
        <li>
          <strong>We route you out.</strong> Every link opens the retailer's own page in a new tab.
          The retailer owns the price, availability and checkout.
        </li>
      </ol>

      <h2>What we do not claim</h2>
      <p>
        Boughtique does not currently hold product-level data, so it publishes no product prices, no
        discount percentages and no stock status. Where a link is labelled a sale or outlet section,
        that means exactly one thing: the retailer itself operates that URL as a reduced section.
        The size and quality of any reduction is the retailer's claim, not ours.
      </p>
      <p>
        We also do not claim that this site uses AI. It does not, yet. When machine learning does
        classify, score or rank what you see, this page will say so and explain what it changes.
      </p>

      <h2>Where this is going</h2>
      <p>The architecture is built for automation, in this order:</p>
      <table>
        <thead>
          <tr>
            <th>Stage</th>
            <th>What it does</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Product ingestion</td>
            <td>Pull retailer and affiliate feeds on a schedule</td>
            <td>Next</td>
          </tr>
          <tr>
            <td>Normalisation</td>
            <td>One schema, one taxonomy, deduplicated across retailers</td>
            <td>Next</td>
          </tr>
          <tr>
            <td>Price history</td>
            <td>Track every observed price so a "deal" can be proven</td>
            <td>Planned</td>
          </tr>
          <tr>
            <td>Deal score</td>
            <td>Rank genuine value, not headline percentages</td>
            <td>Planned</td>
          </tr>
          <tr>
            <td>AI enrichment</td>
            <td>Colour, style and category tagging; natural-language search</td>
            <td>Planned</td>
          </tr>
        </tbody>
      </table>
      <p>
        A deal score will only ever be shown once it is computed from real observed prices. Until
        then, nothing of the kind appears on this site.
      </p>

      <h2>Imagery</h2>
      <p>
        Every image here is abstract artwork generated by Boughtique and served from our own domain.
        It is decorative. It is never a photograph of a product, and it is never presented as one.
        Authorised product photography will only appear via retailer or affiliate feeds that license
        it.
      </p>
    `,
  },

  {
    path: '/contact/',
    eyebrow: 'Contact',
    title: 'Contact',
    metaTitle: 'Contact Boughtique',
    metaDescription: 'Get in touch with Boughtique — press, retailers, partnerships and corrections.',
    lede: 'We read everything.',
    content: html`
      <p>
        Email: <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>
      </p>

      <h3>Retailers and brands</h3>
      <p>
        If you operate a retailer or brand and want your assortment represented accurately — or
        removed — email us and we will action it. We can work from a product feed, a sitemap or an
        affiliate network catalogue.
      </p>

      <h3>Corrections</h3>
      <p>
        Found a broken link, a section that has moved, or anything inaccurate on this site? Tell us
        and we will fix it. Accuracy matters more to us than coverage.
      </p>

      <h3>Press</h3>
      <p>Same address. We will respond with whatever we can verify.</p>
    `,
  },

  {
    path: '/affiliate-disclosure/',
    eyebrow: 'Disclosure',
    title: 'Affiliate disclosure',
    metaTitle: 'Affiliate disclosure — Boughtique',
    metaDescription:
      'Boughtique currently earns no commission from any link on this site. Our full position on affiliate monetisation.',
    lede: 'Plainly: we currently earn nothing from the links on this site.',
    content: html`
      <h2>Current position</h2>
      <p>
        As of today, Boughtique has <strong>no affiliate relationship with any retailer or brand</strong>
        listed on this site. The links you click are ordinary links to public retailer pages. They
        carry no affiliate tracking parameters, and no commission is generated when you use them.
      </p>

      <h2>What we intend</h2>
      <p>
        Boughtique intends to monetise through affiliate partnerships in future. If that happens,
        Boughtique may receive a commission when a qualifying purchase is made after you follow a
        link from this site. That commission is paid by the retailer out of their margin and never
        increases the price you pay.
      </p>

      <h2>Our commitments</h2>
      <ul>
        <li>
          This page will be updated <em>before</em> any affiliate link goes live, naming the
          networks and retailers involved.
        </li>
        <li>
          Commercial relationships will not determine ranking, inclusion or how prominently
          something is shown. Ranking will follow the published methodology.
        </li>
        <li>Any paid placement, if it ever exists, will be visibly labelled as such.</li>
        <li>We will not describe a retailer as a "partner" unless a contract exists.</li>
      </ul>

      <h2>Prices and availability</h2>
      <p>
        Boughtique does not set, control or guarantee any price, discount or stock level. The
        retailer's own page is always the source of truth at the moment of purchase.
      </p>

      <p>Questions about this? <a href="/contact/">Contact us</a>.</p>
    `,
  },

  {
    path: '/privacy/',
    eyebrow: 'Legal',
    title: 'Privacy',
    metaTitle: 'Privacy — Boughtique',
    metaDescription: 'How Boughtique handles data: no accounts, no tracking cookies, no analytics vendor today.',
    lede: 'Short, because we collect almost nothing.',
    content: html`
      <h2>What we collect</h2>
      <p>
        Nothing that identifies you. Boughtique has no accounts, no sign-up, no newsletter capture
        and no advertising or analytics vendor loaded on this site today. We set no cookies.
      </p>

      <h2>Saved discoveries</h2>
      <p>
        When you save an item, its identifier is written to your browser's
        <code>localStorage</code> under the key <code>boughtique.saved.v1</code>. This never leaves
        your device and we cannot read it. Clearing your browser data removes it.
      </p>

      <h2>Hosting logs</h2>
      <p>
        This site is served as static files by GitHub Pages. GitHub processes standard server
        request data (including IP address) to deliver the site and protect it from abuse, under
        their own privacy practices. We do not have access to per-visitor logs.
      </p>

      <h2>Analytics in future</h2>
      <p>
        We expect to add privacy-respecting, aggregate analytics — measuring which sections and
        links are useful, not who you are. When that happens this page will name the provider before
        it is enabled, and we will prefer a cookieless, EU-hosted option.
      </p>

      <h2>Leaving the site</h2>
      <p>
        Links to retailers open on their domains, where their own privacy policies and cookies
        apply. We have no control over and take no responsibility for those.
      </p>

      <h2>Your rights</h2>
      <p>
        Under the GDPR you have rights of access, rectification and erasure. Since we hold no
        personal data about you, there is in practice nothing to request — but if you believe
        otherwise, email <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>.
      </p>
    `,
  },

  {
    path: '/terms/',
    eyebrow: 'Legal',
    title: 'Terms',
    metaTitle: 'Terms of use — Boughtique',
    metaDescription: 'Terms of use for Boughtique, an independent fashion discovery service.',
    lede: 'Using this site means accepting these terms.',
    content: html`
      <h2>What this service is</h2>
      <p>
        Boughtique is an informational discovery service. We do not sell goods, process payments,
        hold stock, or act as an agent of any retailer. Every purchase is a contract between you and
        the retailer, governed by their terms.
      </p>

      <h2>Accuracy</h2>
      <p>
        We work to keep links and descriptions accurate, but retailers restructure their sites and
        change their assortments constantly. Content is provided "as is" without warranty. If you
        find something wrong, <a href="/contact/">tell us</a> and we will correct it.
      </p>

      <h2>No price guarantees</h2>
      <p>
        Boughtique does not publish product prices. Where a section is described as a sale or outlet
        section, that reflects how the retailer operates that page. Any price, reduction or
        availability you ultimately see is determined entirely by the retailer.
      </p>

      <h2>Third-party links and trade marks</h2>
      <p>
        Retailer and brand names are the trade marks of their respective owners and are used
        nominatively to describe where a link goes. Their use does not imply any affiliation,
        sponsorship or endorsement.
      </p>

      <h2>Liability</h2>
      <p>
        To the extent permitted by law, Boughtique is not liable for losses arising from use of this
        site or from any transaction with a retailer reached through it. Nothing here excludes
        liability that cannot lawfully be excluded.
      </p>

      <h2>Changes</h2>
      <p>
        These terms may change as the service develops. The version published here is the one that
        applies.
      </p>
    `,
  },
];
